#!/usr/bin/python
''' Project Euler - Problem 12 (Leonardo Dias - 14/05/2020)

    The sequence of triangle numbers is generated by adding the natural numbers.
    So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
        1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
    Let us list the factors of the first seven triangle numbers:
        1:  1
        3:  1, 3
        6:  1, 2, 3,  6
        10: 1, 2, 5, 10
        15: 1, 3, 5, 15
        21: 1, 3, 7, 21
        28: 1, 2, 4,  7, 14, 28
    We can see that 28 is the first triangle number to have over five divisors.
    What is the value of the first triangle number to have over five hundred divisors?

'''


def Numdivisors(number):
    nDivisors=1
    # Primos
    for i in range(1, number//2+1):
        if number%i==0: nDivisors+=1
    return nDivisors


if __name__=='__main__':
    N_DIVISORS = 5e3

    i, s = 1, 0
    while Numdivisors(s)<N_DIVISORS:
        s += i
        i += 1
        if Numdivisors(s)>100: print(Numdivisors(s))
    print(s)
